version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: chegoudelivery_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chegoudelivery
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: chegoudelivery_redis
    ports:
      - "6379:6379"